### ISSUE TITLE
Minicat Web

### ISSUE THREAD

**Issue by lluiscab** [biels/Minicat-2.0#2]
So here's a little schema for the website.

> Ignore the '?' symbol at Elo
> ![minicat](https://cloud.githubusercontent.com/assets/7149212/13469763/00c691d6-e0a9-11e5-8c8a-2103a9ede9be.png)

**Comment by biels** [comment]
That is ok as a general idea. However, many key points have to be kept in mind.
The statistic system should be simple and scalable to new game modes without effort. It should distinguish between game types. 
For example:
- Team configuration: fixed_team_count / fixed_team_size
- Goal: score_race / objective
- ...

Note that every game will be playable in many modes configurable on gamer creation. Everything in this cartegory has to be detailed in-depth in the game controller section.

As a result of this, the statistic system will depend on the information avaliable on other controllers.

Everything else is fine.

**Comment by lluiscab** [comment]
![1](http://i.imgur.com/hQfKTda.jpg)
![1](http://i.imgur.com/5gP8W6D.jpg)
![1](http://i.imgur.com/74IW63M.jpg)
![1](http://i.imgur.com/wcjm3Tp.jpg)

**Comment by lluiscab** [comment]
I'm temporally hosting a 'demo' / Indev site [Here](http://lluiscab.github.io)

**Comment by biels** [comment]
Okay, I'll add a link to it on readme.md
